/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppBudgetRouteImport } from './routes/app/budget'
import { Route as AppCategoriesRouteImport } from './routes/app/categories'
import { Route as AppDebtsRouteImport } from './routes/app/debts'
import { Route as AppIncomeSourcesRouteImport } from './routes/app/income-sources'
import { Route as AppReconcileRouteImport } from './routes/app/reconcile'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppDebtsIndexRouteImport } from './routes/app/debts.index'
import { Route as AppDebtsDebtIdRouteImport } from './routes/app/debts.$debtId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtsRoute = AppDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeSourcesRoute = AppIncomeSourcesRouteImport.update({
  id: '/income-sources',
  path: '/income-sources',
  getParentRoute: () => AppRoute,
} as any)
const AppReconcileRoute = AppReconcileRouteImport.update({
  id: '/reconcile',
  path: '/reconcile',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDebtsIndexRoute = AppDebtsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDebtsRoute,
} as any)
const AppDebtsDebtIdRoute = AppDebtsDebtIdRouteImport.update({
  id: '/$debtId',
  path: '/$debtId',
  getParentRoute: () => AppDebtsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/debts': typeof AppDebtsRouteWithChildren
  '/app/income-sources': typeof AppIncomeSourcesRoute
  '/app/reconcile': typeof AppReconcileRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/debts/$debtId': typeof AppDebtsDebtIdRoute
  '/app/debts/': typeof AppDebtsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/income-sources': typeof AppIncomeSourcesRoute
  '/app/reconcile': typeof AppReconcileRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/debts/$debtId': typeof AppDebtsDebtIdRoute
  '/app/debts': typeof AppDebtsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/categories': typeof AppCategoriesRoute
  '/app/debts': typeof AppDebtsRouteWithChildren
  '/app/income-sources': typeof AppIncomeSourcesRoute
  '/app/reconcile': typeof AppReconcileRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/debts/$debtId': typeof AppDebtsDebtIdRoute
  '/app/debts/': typeof AppDebtsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/budget'
    | '/app/categories'
    | '/app/debts'
    | '/app/income-sources'
    | '/app/reconcile'
    | '/app/'
    | '/api/auth/$'
    | '/app/debts/$debtId'
    | '/app/debts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/app/budget'
    | '/app/categories'
    | '/app/income-sources'
    | '/app/reconcile'
    | '/app'
    | '/api/auth/$'
    | '/app/debts/$debtId'
    | '/app/debts'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/app/budget'
    | '/app/categories'
    | '/app/debts'
    | '/app/income-sources'
    | '/app/reconcile'
    | '/app/'
    | '/api/auth/$'
    | '/app/debts/$debtId'
    | '/app/debts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/budget': {
      id: '/app/budget'
      path: '/budget'
      fullPath: '/app/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/categories': {
      id: '/app/categories'
      path: '/categories'
      fullPath: '/app/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debts': {
      id: '/app/debts'
      path: '/debts'
      fullPath: '/app/debts'
      preLoaderRoute: typeof AppDebtsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/income-sources': {
      id: '/app/income-sources'
      path: '/income-sources'
      fullPath: '/app/income-sources'
      preLoaderRoute: typeof AppIncomeSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reconcile': {
      id: '/app/reconcile'
      path: '/reconcile'
      fullPath: '/app/reconcile'
      preLoaderRoute: typeof AppReconcileRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/debts/': {
      id: '/app/debts/'
      path: '/'
      fullPath: '/app/debts/'
      preLoaderRoute: typeof AppDebtsIndexRouteImport
      parentRoute: typeof AppDebtsRoute
    }
    '/app/debts/$debtId': {
      id: '/app/debts/$debtId'
      path: '/$debtId'
      fullPath: '/app/debts/$debtId'
      preLoaderRoute: typeof AppDebtsDebtIdRouteImport
      parentRoute: typeof AppDebtsRoute
    }
  }
}

interface AppDebtsRouteChildren {
  AppDebtsDebtIdRoute: typeof AppDebtsDebtIdRoute
  AppDebtsIndexRoute: typeof AppDebtsIndexRoute
}

const AppDebtsRouteChildren: AppDebtsRouteChildren = {
  AppDebtsDebtIdRoute: AppDebtsDebtIdRoute,
  AppDebtsIndexRoute: AppDebtsIndexRoute,
}

const AppDebtsRouteWithChildren = AppDebtsRoute._addFileChildren(
  AppDebtsRouteChildren,
)

interface AppRouteChildren {
  AppBudgetRoute: typeof AppBudgetRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDebtsRoute: typeof AppDebtsRouteWithChildren
  AppIncomeSourcesRoute: typeof AppIncomeSourcesRoute
  AppReconcileRoute: typeof AppReconcileRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetRoute: AppBudgetRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppDebtsRoute: AppDebtsRouteWithChildren,
  AppIncomeSourcesRoute: AppIncomeSourcesRoute,
  AppReconcileRoute: AppReconcileRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
